CREATE TABLE IF NOT EXISTS `groups` (
	`id` BIGINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100) NOT NULL,
	`image` BLOB NOT NULL,
	`description` VARCHAR(255) NOT NULL,
	`enabled` BOOLEAN DEFAULT TRUE NOT NULL,
	`created_date` DATETIME(6) NOT NULL,
    `updated_date` DATETIME(6) NOT NULL,
	UNIQUE `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;