// <auto-generated />
using System;
using ListGenius.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListGenius.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240604213247_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ListGenius.Api.Entities.ProductGroups.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7504),
                            Description = "GERAL",
                            Enabled = true,
                            Image = new byte[] { 0 },
                            Name = "GERAL",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7516)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("product_sub_groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7563),
                            Description = "GERAL",
                            Enabled = true,
                            IdProductGroup = 1,
                            Image = new byte[] { 0 },
                            Name = "GERAL",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7563)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductSubGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductsList")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.HasIndex("IdProductSubGroup");

                    b.HasIndex("IdProductsList");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7740),
                            Description = "TESTE 1",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 1",
                            Qrcode = new byte[] { 0 },
                            Unit = "Meter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7741),
                            Value = 22.05m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7743),
                            Description = "TESTE 2",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 2",
                            Qrcode = new byte[] { 0 },
                            Unit = "SquareMeter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7743),
                            Value = 33.33m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7745),
                            Description = "TESTE 3",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 3",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7745),
                            Value = 42.33m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7746),
                            Description = "TESTE 4",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 4",
                            Qrcode = new byte[] { 0 },
                            Unit = "CubicMeter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7746),
                            Value = 77.77m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7747),
                            Description = "TESTE 5",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 5",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unit",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7748),
                            Value = 66.66m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7749),
                            Description = "TESTE 6",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 6",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7749),
                            Value = 35.31m
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ExternalLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Public")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("products_lists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7589),
                            Description = "Description for Shopping List 1",
                            ExternalLink = "",
                            IdUser = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Image = new byte[] { 0 },
                            Name = "Shopping List 1",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7590)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7591),
                            Description = "Description for Shopping List 2",
                            ExternalLink = "",
                            IdUser = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Image = new byte[] { 0 },
                            Name = "Shopping List 2",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7591)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsShared.ProductShared", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductSubGroup")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.HasIndex("IdProductSubGroup");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("products_shared", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7612),
                            Description = "TESTE 1",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 1",
                            Qrcode = new byte[] { 0 },
                            Unit = "Meter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7613),
                            Value = 22.05m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7618),
                            Description = "TESTE 2",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 2",
                            Qrcode = new byte[] { 0 },
                            Unit = "SquareMeter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7619),
                            Value = 33.33m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7620),
                            Description = "TESTE 3",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 3",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7620),
                            Value = 42.33m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7621),
                            Description = "TESTE 4",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 4",
                            Qrcode = new byte[] { 0 },
                            Unit = "CubicMeter",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7622),
                            Value = 77.77m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7697),
                            Description = "TESTE 5",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 5",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unit",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7698),
                            Value = 66.66m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7699),
                            Description = "TESTE 6",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 6",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 6, 4, 18, 32, 46, 127, DateTimeKind.Local).AddTicks(7700),
                            Value = 35.31m
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("LogoImage")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddcce1c5-dedc-4b15-bd0d-2459eae1eca3",
                            Email = "jmmatheus23@gmail.com",
                            EmailConfirmed = true,
                            FullName = "JoaoDiasUser",
                            LockoutEnabled = false,
                            LogoImage = new byte[0],
                            NormalizedEmail = "JMMATHEUS23@GMAIL.COM",
                            NormalizedUserName = "JMMATHEUS23@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELyEP47grXttIRiAMMJQ+1VhMK7etybhEwlVEXNxiY72zvE1MFZdDCVj8+EPS2iIEA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "019fb84c-b01c-47dd-8e24-cba7bde88427",
                            TwoFactorEnabled = false,
                            UserName = "jmmatheus23@gmail.com"
                        },
                        new
                        {
                            Id = "38846734-172e-4149-8cec-6f43d1eb3f60",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35668527-62b2-4c59-8b7c-44e5e16143a8",
                            Email = "joaodiasworking@gmail.com",
                            EmailConfirmed = true,
                            FullName = "JoaoDiasAdmin",
                            LockoutEnabled = false,
                            LogoImage = new byte[0],
                            NormalizedEmail = "JOAODIASWORKING@GMAIL.COM",
                            NormalizedUserName = "JOAODIASWORKING@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIii4mVINuVD04Umus7e/reoOzNZNy0404aq55WvWxIU+gtXCbM0JXz5xHjd1DAQJw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "7163a134-2c7d-4bdd-ac47-b81aeafc8948",
                            TwoFactorEnabled = false,
                            UserName = "joaodiasworking@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "38846734-172e-4149-8cec-6f43d1eb3f60",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("ProductSubGroups")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Products.Product", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", "ProductSubGroup")
                        .WithMany("Products")
                        .HasForeignKey("IdProductSubGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductsLists.ProductsList", "ProductsList")
                        .WithMany("Products")
                        .HasForeignKey("IdProductsList")
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("ProductSubGroup");

                    b.Navigation("ProductsList");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", "User")
                        .WithMany("ProductsLists")
                        .HasForeignKey("IdUser")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsShared.ProductShared", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("ProductsShared")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", "ProductSubGroup")
                        .WithMany("ProductsShared")
                        .HasForeignKey("IdProductSubGroup")
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("ProductSubGroup");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductGroups.ProductGroup", b =>
                {
                    b.Navigation("ProductSubGroups");

                    b.Navigation("Products");

                    b.Navigation("ProductsShared");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ProductsShared");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("ProductsLists");
                });
#pragma warning restore 612, 618
        }
    }
}
