// <auto-generated />
using System;
using ListGenius.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListGenius.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530231415_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ListGenius.Api.Entities.ProductGroups.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 5, DateTimeKind.Local).AddTicks(7313),
                            Description = "GERAL",
                            Enabled = true,
                            Image = new byte[] { 0 },
                            Name = "GERAL",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 5, DateTimeKind.Local).AddTicks(7331)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.ToTable("ProductSubGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(338),
                            Description = "GERAL",
                            Enabled = true,
                            IdProductGroup = 1,
                            Image = new byte[] { 0 },
                            Name = "GERAL",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(345)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductSubGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductsList")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.HasIndex("IdProductSubGroup");

                    b.HasIndex("IdProductsList");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(666),
                            Description = "TESTE 1",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 1",
                            Qrcode = new byte[] { 0 },
                            Unit = "Meter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(667),
                            Value = 22.05m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(670),
                            Description = "TESTE 2",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 2",
                            Qrcode = new byte[] { 0 },
                            Unit = "SquareMeter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(670),
                            Value = 33.33m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(672),
                            Description = "TESTE 3",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 3",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(672),
                            Value = 42.33m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(673),
                            Description = "TESTE 4",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 4",
                            Qrcode = new byte[] { 0 },
                            Unit = "CubicMeter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(674),
                            Value = 77.77m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(675),
                            Description = "TESTE 5",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 5",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unit",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(686),
                            Value = 66.66m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(694),
                            Description = "TESTE 6",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            IdProductsList = 2,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 6",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(695),
                            Value = 35.31m
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ExternalLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Public")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("ProductsLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(536),
                            Description = "Description for Shopping List 1",
                            ExternalLink = "",
                            IdUser = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Image = new byte[] { 0 },
                            Name = "Shopping List 1",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(536)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(539),
                            Description = "Description for Shopping List 2",
                            ExternalLink = "",
                            IdUser = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Image = new byte[] { 0 },
                            Name = "Shopping List 2",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(539)
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsShared.ProductShared", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("IdProductGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdProductSubGroup")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Qrcode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varbinary(500)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductGroup");

                    b.HasIndex("IdProductSubGroup");

                    b.ToTable("ProductsShared");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(593),
                            Description = "TESTE 1",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 1",
                            Qrcode = new byte[] { 0 },
                            Unit = "Meter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(593),
                            Value = 22.05m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(599),
                            Description = "TESTE 2",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 2",
                            Qrcode = new byte[] { 0 },
                            Unit = "SquareMeter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(599),
                            Value = 33.33m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(600),
                            Description = "TESTE 3",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 3",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(601),
                            Value = 42.33m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(602),
                            Description = "TESTE 4",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 4",
                            Qrcode = new byte[] { 0 },
                            Unit = "CubicMeter",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(602),
                            Value = 77.77m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(604),
                            Description = "TESTE 5",
                            Enabled = true,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 5",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unit",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(604),
                            Value = 66.66m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(605),
                            Description = "TESTE 6",
                            Enabled = false,
                            IdProductGroup = 1,
                            IdProductSubGroup = 1,
                            Image = new byte[] { 0 },
                            Link = "",
                            Name = "Teste 6",
                            Qrcode = new byte[] { 0 },
                            Unit = "Unspecified",
                            UpdatedDate = new DateTime(2024, 5, 30, 20, 14, 14, 6, DateTimeKind.Local).AddTicks(605),
                            Value = 35.31m
                        });
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("LogoImage")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b2ba403-1b8a-45ac-9a3c-a994d005480e",
                            Email = "jmmatheus23@gmail.com",
                            EmailConfirmed = true,
                            FullName = "JoaoDiasUser",
                            LockoutEnabled = false,
                            LogoImage = new byte[0],
                            NormalizedEmail = "JMMATHEUS23@GMAIL.COM",
                            NormalizedUserName = "JMMATHEUS23@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKw1t89fI3j5JucI0wgIiekT9l2ndJUD4EqhCdF77bIlowPbv6U0LJR6/Rc013LnWg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "2d4ddd65-e775-4edd-ae59-24faea591560",
                            TwoFactorEnabled = false,
                            UserName = "jmmatheus23@gmail.com"
                        },
                        new
                        {
                            Id = "38846734-172e-4149-8cec-6f43d1eb3f60",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f677842d-363c-4936-be9a-dbfbe6e3e0bb",
                            Email = "joaodiasworking@gmail.com",
                            EmailConfirmed = true,
                            FullName = "JoaoDiasAdmin",
                            LockoutEnabled = false,
                            LogoImage = new byte[0],
                            NormalizedEmail = "JOAODIASWORKING@GMAIL.COM",
                            NormalizedUserName = "JOAODIASWORKING@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECDJymsYPgOYIdp5xaxVK1aiAALZ2bm9s2xfUH1tztJuPMfWK5E0b8jWSux+hLz4MA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = new byte[0],
                            SecurityStamp = "cef11e26-55a6-4317-bb6b-a18cfe5d0158",
                            TwoFactorEnabled = false,
                            UserName = "joaodiasworking@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "38846734-172e-4149-8cec-6f43d1eb3f60",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("ProductSubGroups")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Products.Product", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", "ProductSubGroup")
                        .WithMany("Products")
                        .HasForeignKey("IdProductSubGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductsLists.ProductsList", "ProductsList")
                        .WithMany("Products")
                        .HasForeignKey("IdProductsList")
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("ProductSubGroup");

                    b.Navigation("ProductsList");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", "User")
                        .WithMany("ProductsLists")
                        .HasForeignKey("IdUser")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsShared.ProductShared", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.ProductGroups.ProductGroup", "ProductGroup")
                        .WithMany("ProductsShared")
                        .HasForeignKey("IdProductGroup")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", "ProductSubGroup")
                        .WithMany("ProductsShared")
                        .HasForeignKey("IdProductSubGroup")
                        .IsRequired();

                    b.Navigation("ProductGroup");

                    b.Navigation("ProductSubGroup");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ListGenius.Api.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductGroups.ProductGroup", b =>
                {
                    b.Navigation("ProductSubGroups");

                    b.Navigation("Products");

                    b.Navigation("ProductsShared");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductSubGroups.ProductSubGroup", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("ProductsShared");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.ProductsLists.ProductsList", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ListGenius.Api.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("ProductsLists");
                });
#pragma warning restore 612, 618
        }
    }
}
