version: '3.4'

services:
  db:
    image: ${DOCKER_REGISTRY-}joaodiasdev-list-genius-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./backend
      dockerfile: DockerFiles/db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: joaodiasdev!#$%@16048888
      MYSQL_USER: docker
      MYSQL_PASSWORD: joaodiasdev!#$%@AMD1604!!@
      MYSQL_DATABASE: joaodiasdev-list-genius
    ports:
     - 3308:3306
    networks:
     - joaodiasdev-list-genius-network

  joaodiasdev.listgenius:
    image: ${DOCKER_REGISTRY-}joaodiasdev-list-genius
    build:
      context: ./backend
      dockerfile: Dockerfiles/joaodiasdev-list-genius/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
     - 7093:80
    depends_on:
     - db
    networks:
     - joaodiasdev-list-genius-network
networks:
  joaodiasdev-list-genius-network:
    driver: bridge